In [1]:
import numpy as np
import objectiveFunctions
import BFGS
import gradientDescent

The first problem we look at is the problem of a cable net described by the following parameters:
$$ 
\begin{equation}
    \begin{split}
        p^{(1)} = (5, 5, 0),\quad p^{(2)} = (-5, 5, 0), &\quad p^{(3)} = (-5, -5, 0), \quad p^{(4)} = (5, -5, 0) \\
        m_i g = \frac{1}{6}, \quad i=5&,6,7,8 \quad,\quad k=1 \\
        l_{15} = l_{26} = l_{37} = l_{48} = &l_{56} = l_{67} = l_{78} = l_{58} = 3
    \end{split}
\end{equation}
$$

This problem is set up as the *objectiveFunctionP5* object *P5* in the file *objectiveFunctions*. First we test the value function as well as the gradient at the provided analytical solution, defined in the following *X_star*:

In [2]:
X_star = np.array([2, 2, -3/2,-2, 2, -3/2,-2, -2, -3/2,2, -2, -3/2])    # The analytical solution
print(f'''The value of the function at the analytical solution. 
It should be about equal to {7/6}.\nE_P5={objectiveFunctions.P5.getVal(X_star)}''')            # The value of the function at X^* should be about 7/6
print(f'The gradient at the analytical solution, which should be about zero in all directions.')
print(objectiveFunctions.P5.getGrad(X_star)) # The gradient should equal zero at X^*


The value of the function at the analytical solution. 
It should be about equal to 1.1666666666666667.
E_P5=1.666666666666667
The gradient at the analytical solution, which should be about zero in all directions.
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


This looks good so we move on to using optimization methods on the problems. First we test a much simpler problem: two nodes floating above ground, with cables to one free node between them:
$$ 
\begin{equation}
    \begin{split}
        p^{(1)} = (1, 0, 3),\quad &p^{(2)} = (-1, 0, 3) \\
        l_{13} = l_{23} = 1 \quad&,\quad m_3 g = 1
    \end{split}
\end{equation}
$$

In [17]:
print('X_sol:\n',BFGS.BFGS(objectiveFunctions.testOF.getVal,objectiveFunctions.testOF.getGrad,np.zeros(3)))

The algorithm converged after 9 iterations.
X_sol:
 [0.         0.         2.21667555]


As expected the free node hangs between the fixed nodes. Next we find a solution o the original system, from a random initialization - for simplicity we place all the free nodes at the origin, and use the BFGS method to solve the problem:

In [3]:
X_0 = np.zeros(3*4)
print('BFGS: X_sol:\n',BFGS.BFGS(objectiveFunctions.P5.getVal,objectiveFunctions.P5.getGrad,X_0))

The algorithm converged after 21 iterations.
BFGS: X_sol:
 [ 2.00000004  2.00000004 -1.49999698 -2.00000004  2.00000004 -1.49999698
 -2.00000004 -2.00000004 -1.49999698  2.00000004 -2.00000004 -1.49999698]


This is as expected, it is the analytical solution, with only minor numerical inaccuracies. For comparison of the effectiveness of the BFGS method we use the gradient descent method also on the same problem:

In [4]:
print('Gradient descent: X_sol:\n',gradientDescent.gradientDescent(objectiveFunctions.P5.getVal,objectiveFunctions.P5.getGrad,X_0,maxSteps=1000,rho=0.9))

The algorithm converged after 771 iterations
Gradient descent: X_sol:
 [ 1.99999978  1.99999978 -1.49999617 -1.99999978  1.99999978 -1.49999617
 -1.99999978 -1.99999978 -1.49999617  1.99999978 -1.99999978 -1.49999617]


This used far more iterations to reach the solution, as we woukld expect.

Moving on to tensegrity domes, where there are fixed nodes and bars. A system with a known analytical solution is given by the following parameters:

$$
\begin{equation}
    \begin{split}
        p^{(1)} = (1, 1, 0),\quad p^{(2)} = (-1, 1, 0), &\quad p^{(3)} = (-1, -1, 0), \quad p^{(4)} = (1, -1, 0) \\
        m_i g = 0, \quad i=5,6,7,8,\quad &k=0.1, \quad c=1, \quad g\rho = 0 \\
        \text{Bars at: } l_{15} = l_{26} = &l_{37} = l_{48} = 10 \\
        \text{Cables at: } l_{18} = l_{25} = l_{36} = l_{47}& = 8, \quad l_{56} = l_{67} = l_{78} = l_{58} = 1 \\
    \end{split}
\end{equation}
$$

We again test the gradient at the provided analytical solution *X_star*:

In [5]:
X_star = np.array([-0.70970,0,9.54287,0,-0.70970,9.54287,0.70970,0,9.54287,0,0.70970,9.54287]) # The approximate analytical solution of problem 9
print(f'The gradient at the analytical solution. Should be about equal to zero.')
print(objectiveFunctions.P9.getGrad(X_star))

The gradient at the analytical solution. Should be about equal to zero.
[ 2.06271080e-06  3.13847095e-09 -2.99500203e-08 -3.13847095e-09
  2.06271080e-06 -2.99500203e-08 -2.06271080e-06 -3.13847095e-09
 -2.99500203e-08  3.13847095e-09 -2.06271080e-06 -2.99500203e-08]


As expected, the gradient at the solution is about equal to zero, so we proceed to use the BFGS method on the problem to see what solutions it may admit. We test two different initializations *X_1* and *X_2*:

In [6]:
X_1 = np.ones(3*4) * -1
print(f'Using BFGS on problem 9, with the the inital X=\n{X_1}')
print('X_sol:\n',BFGS.BFGS(objectiveFunctions.P9.getVal,objectiveFunctions.P9.getGrad,X_1,maxItr=10000))

Using BFGS on problem 9, with the the inital X=
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
The algorithm converged after 3076 iterations.
X_sol:
 [-7.09728435e-01 -1.17660014e-04 -9.54284775e+00 -9.19409756e-06
 -7.09815069e-01 -9.54282426e+00  7.09587426e-01  2.52504278e-06
 -9.54293018e+00 -1.31106841e-04  7.09705224e-01 -9.54286915e+00]


In [7]:
X_2 = np.ones(3*4) #np.array([2,0,10,2,0,10,2,0,10,2,0,10])
print(f'Using BFGS on problem 9, with the the inital X=\n{X_2}')
print('X_sol:\n',BFGS.BFGS(objectiveFunctions.P9.getVal,objectiveFunctions.P9.getGrad,X_2,maxItr=10000))

Using BFGS on problem 9, with the the inital X=
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The algorithm converged after 3059 iterations.
X_sol:
 [-7.09724380e-01 -1.76224101e-04  9.54289561e+00  1.61709553e-05
 -7.09858500e-01  9.54282372e+00  7.09577759e-01 -4.35121672e-07
  9.54287159e+00 -1.61855422e-04  7.09675985e-01  9.54286262e+00]


The first one of these is a rather boring solution, as the nodes are just hanging down. The second is however more interesting, here the nodes are keopt above the fixed nodes by the tension of the cables, and the integrity of the bars. In other words, the forces acting upon the nodes are net zero, as the as the forces counteract each other perfectly, keeping the structure from collapsing.